GoEngineerCodingExample/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoEngineerCodingExample.Database;
using GoEngineerCodingExample.Models;
using GoEngineerCodingExample.Tools;

namespace GoEngineerCodingExample.Controllers
{
    public class PeopleController : Controller
    {
        private readonly DataContext _context;

        public PeopleController(DataContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await _context.People.ToListAsync());
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (people == null)
            {
                return NotFound();
            }

            people.HomeworldLink = LinkHelper.GetPlanetLink(_context.Planets.FirstOrDefault(planet => planet.url == people.homeworld));
            people.SpeciesLinks = LinkHelper.GetSpeciesLinks(_context.Species.Where(species => people.species.Contains(species.url)).ToList());
            people.StarShipLinks = LinkHelper.GetStarShipLinks(_context.StarShips.Where(starship => people.starships.Contains(starship.url)).ToList());
            people.VehicleLinks = LinkHelper.GetVehicleLinks(_context.Vehicles.Where(vehicle => people.vehicles.Contains(vehicle.url)).ToList());
            people.FilmLinks = LinkHelper.GetFilmLinks(_context.Films.Where(film => people.films.Contains(film.url)).ToList());

            return View(people);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            PeopleModel model = new PeopleModel();
            model.HomeworldOptions = _context.Planets.OrderBy(planet => planet.name).ToList();
            model.SpeciesOptions = _context.Species.OrderBy(species => species.name).ToList();
            model.StarShipOptions = _context.StarShips.OrderBy(starShip => starShip.name).ToList();
            model.VehicleOptions = _context.Vehicles.OrderBy(vehicles => vehicles.name).ToList();
            model.FilmOptions = _context.Films.OrderBy(film => film.episode_id).ToList();
            return View(model);
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url")] PeopleModel people, string SelectedHomeworld, List<string> selectedFilms, List<string> selectedSpecies, List<string> selectedVehicles, List<string> selectedStarShips)
        {
            if (ModelState.IsValid)
            {
                people.homeworld = SelectedHomeworld;
                people.films = selectedFilms;
                people.species = selectedSpecies;
                people.starships = selectedStarShips;
                people.vehicles = selectedVehicles;

                _context.Add(people);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(people);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People.FindAsync(id);
            if (people == null)
            {
                return NotFound();
            }

            people.HomeworldOptions = _context.Planets.OrderBy(planet => planet.name).ToList();
            people.SpeciesOptions = _context.Species.OrderBy(species => species.name).ToList();
            people.StarShipOptions = _context.StarShips.OrderBy(starShip => starShip.name).ToList();
            people.VehicleOptions = _context.Vehicles.OrderBy(vehicles => vehicles.name).ToList();
            people.FilmOptions = _context.Films.OrderBy(film => film.episode_id).ToList();

            return View(people);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url")] PeopleModel people, string SelectedHomeworld, List<string> selectedFilms, List<string> selectedSpecies, List<string> selectedVehicles, List<string> selectedStarShips)
        {
            if (id != people.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    people.homeworld = SelectedHomeworld;
                    people.films = selectedFilms;
                    people.species = selectedSpecies;
                    people.starships = selectedStarShips;
                    people.vehicles = selectedVehicles;

                    _context.Update(people);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeopleExists(people.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(people);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (people == null)
            {
                return NotFound();
            }

            people.HomeworldLink = LinkHelper.GetPlanetLink(_context.Planets.FirstOrDefault(planet => planet.url == people.homeworld));
            people.SpeciesLinks = LinkHelper.GetSpeciesLinks(_context.Species.Where(species => people.species.Contains(species.url)).ToList());
            people.StarShipLinks = LinkHelper.GetStarShipLinks(_context.StarShips.Where(starship => people.starships.Contains(starship.url)).ToList());
            people.VehicleLinks = LinkHelper.GetVehicleLinks(_context.Vehicles.Where(vehicle => people.vehicles.Contains(vehicle.url)).ToList());
            people.FilmLinks = LinkHelper.GetFilmLinks(_context.Films.Where(film => people.films.Contains(film.url)).ToList());

            return View(people);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var people = await _context.People.FindAsync(id);
            if (people != null)
            {
                _context.People.Remove(people);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeopleExists(int id)
        {
            return _context.People.Any(e => e.Id == id);
        }
    }
}

GoEngineerCodingExample/Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoEngineerCodingExample.Database;
using GoEngineerCodingExample.Models;
using GoEngineerCodingExample.Tools;

namespace GoEngineerCodingExample.Controllers
{
    public class PlanetController : Controller
    {
        private readonly DataContext _context;

        public PlanetController(DataContext context)
        {
            _context = context;
        }

        // GET: PlanetModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.Planets.ToListAsync());
        }

        // GET: PlanetModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planetModel = await _context.Planets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (planetModel == null)
            {
                return NotFound();
            }

            planetModel.FilmLinks = LinkHelper.GetFilmLinks(_context.Films.Where(film => planetModel.films.Contains(film.url)).ToList());
            planetModel.ResidentLinks = LinkHelper.GetPersonLinks(_context.People.Where(pilot => planetModel.residents.Contains(pilot.url)).ToList());

            return View(planetModel);
        }

        // GET: PlanetModels/Create
        public IActionResult Create()
        {
            PlanetModel model = new PlanetModel();
            model.FilmOptions = _context.Films.OrderBy(film => film.episode_id).ToList();
            model.ResidentOptions = _context.People.OrderBy(person => person.name).ToList();
            return View(model);
        }

        // POST: PlanetModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url")] PlanetModel planetModel, List<string> selectedFilms, List<string> selectedResidents)
        {
            if (ModelState.IsValid)
            {
                planetModel.residents = selectedResidents;
                planetModel.films = selectedFilms;
                _context.Add(planetModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(planetModel);
        }

        // GET: PlanetModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planetModel = await _context.Planets.FindAsync(id);
            if (planetModel == null)
            {
                return NotFound();
            }

            planetModel.FilmOptions = _context.Films.OrderBy(film => film.episode_id).ToList();
            planetModel.ResidentOptions = _context.People.OrderBy(person => person.name).ToList();

            return View(planetModel);
        }

        // POST: PlanetModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url")] PlanetModel planetModel, List<string> selectedFilms, List<string> selectedResidents)
        {
            if (id != planetModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    planetModel.residents = selectedResidents;
                    planetModel.films = selectedFilms;
                    _context.Update(planetModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanetModelExists(planetModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(planetModel);
        }

        // GET: PlanetModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planetModel = await _context.Planets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (planetModel == null)
            {
                return NotFound();
            }

            planetModel.FilmLinks = LinkHelper.GetFilmLinks(_context.Films.Where(film => planetModel.films.Contains(film.url)).ToList());
            planetModel.ResidentLinks = LinkHelper.GetPersonLinks(_context.People.Where(pilot => planetModel.residents.Contains(pilot.url)).ToList());

            return View(planetModel);
        }

        // POST: PlanetModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var planetModel = await _context.Planets.FindAsync(id);
            if (planetModel != null)
            {
                _context.Planets.Remove(planetModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanetModelExists(int id)
        {
            return _context.Planets.Any(e => e.Id == id);
        }
    }
}

GoEngineerCodingExample/Views/Film/Create.cshtml
@model GoEngineerCodingExample.Models.FilmModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Film</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="episode_id" class="control-label"></label>
                <input asp-for="episode_id" class="form-control" />
                <span asp-validation-for="episode_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opening_crawl" class="control-label"></label>
                <input asp-for="opening_crawl" class="form-control" />
                <span asp-validation-for="opening_crawl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="director" class="control-label"></label>
                <input asp-for="director" class="form-control" />
                <span asp-validation-for="director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="producer" class="control-label"></label>
                <input asp-for="producer" class="form-control" />
                <span asp-validation-for="producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="release_date" class="control-label"></label>
                <input asp-for="release_date" class="form-control" />
                <span asp-validation-for="release_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="characters" class="control-label"></label>
            </div>
            <div class="d-flex flex-wrap">
                @foreach (var character in Model.CharacterOptions)
                {
                    <div style="margin-right: 15px">
                        <input class="form-check-input" type="checkbox" value="@character.url" name="selectedCharacters" id="characteritem-@character.Id">
                        <label class="form-check-label" for="characteritem-@character.Id" style="margin-left: 5px">
                            @character.name
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <label asp-for="planets" class="control-label"></label>
            </div>
            <div class="d-flex flex-wrap">
                @foreach (var planet in Model.PlanetOptions)
                {
                    <div style="margin-right: 15px">
                        <input class="form-check-input" type="checkbox" value="@planet.url" name="selectedPlanets" id="planetitem-@planet.Id">
                        <label class="form-check-label" for="planetitem-@planet.Id" style="margin-left: 5px">
                            @planet.name
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <label asp-for="starships" class="control-label"></label>
            </div>
            <div class="d-flex flex-wrap">
                @foreach (var starship in Model.StarShipOptions)
                {
                    <div style="margin-right: 15px">
                        <input class="form-check-input" type="checkbox" value="@starship.url" name="selectedStarShips" id="starshipitem-@starship.Id">
                        <label class="form-check-label" for="starshipitem-@starship.Id" style="margin-left: 5px">
                            @starship.name
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <label asp-for="vehicles" class="control-label"></label>
            </div>
            <div class="d-flex flex-wrap">
                @foreach (var vehicle in Model.VehicleOptions)
                {
                    <div style="margin-right: 15px">
                        <input class="form-check-input" type="checkbox" value="@vehicle.url" name="selectedVehicles" id="vehicleitem-@vehicle.Id">
                        <label class="form-check-label" for="vehicleitem-@vehicle.Id" style="margin-left: 5px">
                            @vehicle.name
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <label asp-for="species" class="control-label"></label>
            </div>
            <div class="d-flex flex-wrap">
                @foreach (var species in Model.SpeciesOptions)
                {
                    <div style="margin-right: 15px">
                        <input class="form-check-input" type="checkbox" value="@species.url" name="selectedSpecies" id="speciesitem-@species.Id">
                        <label class="form-check-label" for="speciesitem-@species.Id" style="margin-left: 5px">
                            @species.name
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <label asp-for="created" class="control-label"></label>
                <input asp-for="created" class="form-control" />
                <span asp-validation-for="created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="edited" class="control-label"></label>
                <input asp-for="edited" class="form-control" />
                <span asp-validation-for="edited" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="url" class="control-label"></label>
                <input asp-for="url" class="form-control" />
                <span asp-validation-for="url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoEngineerCodingExample/Views/Film/Delete.cshtml
@model GoEngineerCodingExample.Models.FilmModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete @Model.title?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.episode_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.episode_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opening_crawl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opening_crawl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.producer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.producer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.release_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.release_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.characters)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.CharacterLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="People" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.planets)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.PlanetLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Planet" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.starships)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.StarShipLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="StarShipModels" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.vehicles)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.VehicleLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Vehicle" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.species)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.SpeciesLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Species" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.edited)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.edited)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Html.DisplayFor(model => model.url)">View in SWAPI</a>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GoEngineerCodingExample/Views/Film/Details.cshtml
@model GoEngineerCodingExample.Models.FilmModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details for @Model.title</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.episode_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.episode_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opening_crawl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opening_crawl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.producer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.producer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.release_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.release_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.characters)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.CharacterLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="People" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.planets)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.PlanetLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Planet" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.starships)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.StarShipLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="StarShipModels" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.vehicles)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.VehicleLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Vehicle" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.species)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.SpeciesLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Species" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.edited)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.edited)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Html.DisplayFor(model => model.url)">View in SWAPI</a>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GoEngineerCodingExample/Views/Film/Index.cshtml
@model IEnumerable<GoEngineerCodingExample.Models.FilmModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Films</h1>

<p>
    <a asp-action="Create">Create New Film</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                Episode @Html.DisplayNameFor(model => model.episode_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.producer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.release_date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.episode_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.producer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.release_date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>