GoEngineerCodingExample/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoEngineerCodingExample.Database;
using GoEngineerCodingExample.Models;
using GoEngineerCodingExample.Tools;

namespace GoEngineerCodingExample.Controllers
{
    public class FilmController : Controller
    {
        private readonly DataContext _context;

        public FilmController(DataContext context)
        {
            _context = context;
        }

        // GET: Film
        public async Task<IActionResult> Index()
        {
            List<FilmModel> films = await _context.Films.ToListAsync();
            return View(films.OrderBy(film => film.episode_id));
        }

        // GET: Film/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmModel = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filmModel == null)
            {
                return NotFound();
            }

            filmModel.CharacterLinks = LinkHelper.GetPersonLinks(_context.People.Where(character => filmModel.characters.Contains(character.url)).ToList());
            filmModel.PlanetLinks = LinkHelper.GetPlanetLinks(_context.Planets.Where(planet => filmModel.planets.Contains(planet.url)).ToList());
            filmModel.StarShipLinks = LinkHelper.GetStarShipLinks(_context.StarShips.Where(starship => filmModel.starships.Contains(starship.url)).ToList());
            filmModel.VehicleLinks = LinkHelper.GetVehicleLinks(_context.Vehicles.Where(vehicle => filmModel.vehicles.Contains(vehicle.url)).ToList());
            filmModel.SpeciesLinks = LinkHelper.GetSpeciesLinks(_context.Species.Where(species => filmModel.species.Contains(species.url)).ToList());

            return View(filmModel);
        }

        // GET: Film/Create
        public IActionResult Create()
        {
            FilmModel filmModel = new FilmModel();  
            filmModel.CharacterOptions = _context.People.OrderBy(person => person.name).ToList();
            filmModel.PlanetOptions = _context.Planets.OrderBy(planet => planet.name).ToList();
            filmModel.StarShipOptions = _context.StarShips.OrderBy(starShip => starShip.name).ToList();
            filmModel.VehicleOptions = _context.Vehicles.OrderBy(vehicles => vehicles.name).ToList();
            filmModel.SpeciesOptions = _context.Species.OrderBy(species => species.name).ToList();

            return View(filmModel);
        }

        // POST: Film/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,title,episode_id,opening_crawl,director,producer,release_date,characters,planets,starships,vehicles,species,created,edited,url")] FilmModel filmModel, List<string> selectedCharacters, List<string> selectedPlanets, List<string> selectedStarShips, List<string> selectedVehicles, List<string> selectedSpecies)
        {
            if (ModelState.IsValid)
            {
                filmModel.characters = selectedCharacters;
                filmModel.planets = selectedPlanets;
                filmModel.starships = selectedStarShips;
                filmModel.vehicles = selectedVehicles;
                filmModel.species = selectedSpecies;
                _context.Add(filmModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filmModel);
        }

        // GET: Film/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmModel = await _context.Films.FindAsync(id);
            if (filmModel == null)
            {
                return NotFound();
            }

            filmModel.CharacterOptions = _context.People.OrderBy(person => person.name).ToList();
            filmModel.PlanetOptions = _context.Planets.OrderBy(planet => planet.name).ToList();
            filmModel.StarShipOptions = _context.StarShips.OrderBy(starShip => starShip.name).ToList();
            filmModel.VehicleOptions = _context.Vehicles.OrderBy(vehicles => vehicles.name).ToList();
            filmModel.SpeciesOptions = _context.Species.OrderBy(species => species.name).ToList();

            return View(filmModel);
        }

        // POST: Film/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,title,episode_id,opening_crawl,director,producer,release_date,characters,planets,starships,vehicles,species,created,edited,url")] FilmModel filmModel, List<string> selectedCharacters, List<string> selectedPlanets, List<string> selectedStarShips, List<string> selectedVehicles, List<string> selectedSpecies)
        {
            if (id != filmModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    filmModel.characters = selectedCharacters;
                    filmModel.planets = selectedPlanets;
                    filmModel.starships = selectedStarShips;
                    filmModel.vehicles = selectedVehicles;
                    filmModel.species = selectedSpecies;
                    _context.Update(filmModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmModelExists(filmModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filmModel);
        }

        // GET: Film/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmModel = await _context.Films
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filmModel == null)
            {
                return NotFound();
            }

            filmModel.CharacterLinks = LinkHelper.GetPersonLinks(_context.People.Where(character => filmModel.characters.Contains(character.url)).ToList());
            filmModel.PlanetLinks = LinkHelper.GetPlanetLinks(_context.Planets.Where(planet => filmModel.planets.Contains(planet.url)).ToList());
            filmModel.StarShipLinks = LinkHelper.GetStarShipLinks(_context.StarShips.Where(starship => filmModel.starships.Contains(starship.url)).ToList());
            filmModel.VehicleLinks = LinkHelper.GetVehicleLinks(_context.Vehicles.Where(vehicle => filmModel.vehicles.Contains(vehicle.url)).ToList());
            filmModel.SpeciesLinks = LinkHelper.GetSpeciesLinks(_context.Species.Where(species => filmModel.species.Contains(species.url)).ToList());

            return View(filmModel);
        }

        // POST: Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filmModel = await _context.Films.FindAsync(id);
            if (filmModel != null)
            {
                _context.Films.Remove(filmModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmModelExists(int id)
        {
            return _context.Films.Any(e => e.Id == id);
        }
    }
}

GoEngineerCodingExample/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoEngineerCodingExample.Database;
using GoEngineerCodingExample.Models;
using GoEngineerCodingExample.Tools;

namespace GoEngineerCodingExample.Controllers
{
    public class PeopleController : Controller
    {
        private readonly DataContext _context;

        public PeopleController(DataContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await _context.People.ToListAsync());
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (people == null)
            {
                return NotFound();
            }

            people.HomeworldLink = LinkHelper.GetPlanetLink(_context.Planets.FirstOrDefault(planet => planet.url == people.homeworld));
            people.SpeciesLinks = LinkHelper.GetSpeciesLinks(_context.Species.Where(species => people.species.Contains(species.url)).ToList());
            people.StarShipLinks = LinkHelper.GetStarShipLinks(_context.StarShips.Where(starship => people.starships.Contains(starship.url)).ToList());
            people.VehicleLinks = LinkHelper.GetVehicleLinks(_context.Vehicles.Where(vehicle => people.vehicles.Contains(vehicle.url)).ToList());
            people.FilmLinks = LinkHelper.GetFilmLinks(_context.Films.Where(film => people.films.Contains(film.url)).ToList());

            return View(people);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            PeopleModel model = new PeopleModel();
            model.HomeworldOptions = _context.Planets.OrderBy(planet => planet.name).ToList();
            model.SpeciesOptions = _context.Species.OrderBy(species => species.name).ToList();
            model.StarShipOptions = _context.StarShips.OrderBy(starShip => starShip.name).ToList();
            model.VehicleOptions = _context.Vehicles.OrderBy(vehicles => vehicles.name).ToList();
            model.FilmOptions = _context.Films.OrderBy(film => film.episode_id).ToList();
            return View(model);
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url")] PeopleModel people, string SelectedHomeworld, List<string> selectedFilms, List<string> selectedSpecies, List<string> selectedVehicles, List<string> selectedStarShips)
        {
            if (ModelState.IsValid)
            {
                people.homeworld = SelectedHomeworld;
                people.films = selectedFilms;
                people.species = selectedSpecies;
                people.starships = selectedStarShips;
                people.vehicles = selectedVehicles;

                _context.Add(people);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(people);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People.FindAsync(id);
            if (people == null)
            {
                return NotFound();
            }

            people.HomeworldOptions = _context.Planets.OrderBy(planet => planet.name).ToList();
            people.SpeciesOptions = _context.Species.OrderBy(species => species.name).ToList();
            people.StarShipOptions = _context.StarShips.OrderBy(starShip => starShip.name).ToList();
            people.VehicleOptions = _context.Vehicles.OrderBy(vehicles => vehicles.name).ToList();
            people.FilmOptions = _context.Films.OrderBy(film => film.episode_id).ToList();

            return View(people);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url")] PeopleModel people, string SelectedHomeworld, List<string> selectedFilms, List<string> selectedSpecies, List<string> selectedVehicles, List<string> selectedStarShips)
        {
            if (id != people.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    people.homeworld = SelectedHomeworld;
                    people.films = selectedFilms;
                    people.species = selectedSpecies;
                    people.starships = selectedStarShips;
                    people.vehicles = selectedVehicles;

                    _context.Update(people);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeopleExists(people.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(people);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (people == null)
            {
                return NotFound();
            }

            people.HomeworldLink = LinkHelper.GetPlanetLink(_context.Planets.FirstOrDefault(planet => planet.url == people.homeworld));
            people.SpeciesLinks = LinkHelper.GetSpeciesLinks(_context.Species.Where(species => people.species.Contains(species.url)).ToList());
            people.StarShipLinks = LinkHelper.GetStarShipLinks(_context.StarShips.Where(starship => people.starships.Contains(starship.url)).ToList());
            people.VehicleLinks = LinkHelper.GetVehicleLinks(_context.Vehicles.Where(vehicle => people.vehicles.Contains(vehicle.url)).ToList());
            people.FilmLinks = LinkHelper.GetFilmLinks(_context.Films.Where(film => people.films.Contains(film.url)).ToList());

            return View(people);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var people = await _context.People.FindAsync(id);
            if (people != null)
            {
                _context.People.Remove(people);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeopleExists(int id)
        {
            return _context.People.Any(e => e.Id == id);
        }
    }
}

GoEngineerCodingExample/Views/People/Delete.cshtml
@model GoEngineerCodingExample.Models.PeopleModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete @Model.name?</h3>
<div>
    <h4>People</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hair_color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hair_color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.skin_color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.skin_color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.eye_color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.eye_color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.birth_year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.birth_year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.homeworld)
        </dt>
        <dd class = "col-sm-10">
            <a asp-area=" " asp-controller="People" asp-action="Details" asp-route-id="@Model.HomeworldLink.Id">@Model.HomeworldLink.Name</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.films)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.FilmLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Film" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.species)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.SpeciesLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Species" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.vehicles)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.VehicleLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Vehicle" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.starships)
        </dt>
        <dd class = "col-sm-10">
            @foreach (var link in Model.StarShipLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="StarShipModels" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.edited)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.edited)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Html.DisplayFor(model => model.url)">View in SWAPI</a>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GoEngineerCodingExample/Views/People/Details.cshtml
@model GoEngineerCodingExample.Models.PeopleModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details for @Model.name</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hair_color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hair_color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.skin_color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.skin_color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.eye_color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.eye_color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.birth_year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.birth_year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.homeworld)
        </dt>
        <dd class="col-sm-10">
            <a asp-area=" " asp-controller="Planet" asp-action="Details" asp-route-id="@Model.HomeworldLink.Id">@Model.HomeworldLink.Name</a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.films)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.FilmLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Film" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.species)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.SpeciesLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Species" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.vehicles)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.VehicleLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="Vehicle" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.starships)
        </dt>
        <dd class="col-sm-10">
            @foreach (var link in Model.StarShipLinks)
            {
                <li>
                    <a asp-area=" " asp-controller="StarShipModels" asp-action="Details" asp-route-id="@link.Id">@link.Name</a>
                </li>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.edited)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.edited)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url)
        </dt>
        <dd class = "col-sm-10">
            <a href="@Html.DisplayFor(model => model.url)">View in SWAPI</a>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GoEngineerCodingExample/Views/People/Index.cshtml
@model IEnumerable<GoEngineerCodingExample.Models.PeopleModel>

@{
    ViewData["Title"] = "Index";
}

<h1>People</h1>

<p>
    <a asp-action="Create">Create New Person</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hair_color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.skin_color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.eye_color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.birth_year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hair_color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.skin_color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.eye_color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.birth_year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>